/// Flutter icons AppIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData requestManagement = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardDrag = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addItemPlus = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myPage = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData register = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData currentLocation = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData detailView = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dotsVertical = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData itemRegisterHeart = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigateBefore = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onboardingProgressCheck = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData romromRLogoText = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
