// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHPgaOZ8KdNcgRdADyJmXAn9Mul7COq4c',
    appId: '1:905325245238:android:86db75164e0df29a1f3997',
    messagingSenderId: '905325245238',
    projectId: 'romrom-c4008',
    storageBucket: 'romrom-c4008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl2cvhEY8e_0Ff9PatEy9aXwupRyD87uE',
    appId: '1:905325245238:ios:df1935263a97e0f71f3997',
    messagingSenderId: '905325245238',
    projectId: 'romrom-c4008',
    storageBucket: 'romrom-c4008.firebasestorage.app',
    androidClientId: '905325245238-4kasijd8rn05pl8hf12losab56c0kt4b.apps.googleusercontent.com',
    iosClientId: '905325245238-9o9c3a0art9egjpmn964m9ssm4ig7vk8.apps.googleusercontent.com',
    iosBundleId: 'com.alom.romrom',
  );

}