lane :build do
  short_commit_hash = ENV['SHORT_COMMIT_HASH']
  flutter_build(
    build: 'apk',
    project_dir: '..',
    output_name: "romrom-#{short_commit_hash}.apk"
  )
end

def flutter_build(options)
  Dir.chdir(options[:project_dir]) do
    sh(
      "flutter",
      "build",
      options[:build],
      "--release",
      "--no-tree-shake-icons",
      "--target-platform=android-arm64",
      "-v"
    )
  end
  sh("mkdir", "-p", "./app/build/outputs/apk/release/")
  sh("mv", "../build/app/outputs/flutter-apk/app-release.apk", "./app/build/outputs/apk/release/#{options[:output_name]}")
end