lane :build do
  short_commit_hash = ENV['SHORT_COMMIT_HASH']
  flutter_build(
    build: 'apk',
    project_dir: '..',  # Flutter 프로젝트 루트
    output_name: "romrom-#{short_commit_hash}.apk"
  )
end

def flutter_build(options)
  sh(
    "flutter",
    "build",
    options[:build],
    "--release",
    "--split-per-abi",  # 빌드 시간 단축
    "--no-tree-shake-icons",
    "--target-platform=android-arm64",
    "-v"
  )
  sh("mv", "../build/app/outputs/apk/release/app-arm64-v8a-release.apk", "app/build/outputs/apk/release/romrom-#{ENV['SHORT_COMMIT_HASH']}.apk")
end
