name: 자동 버전 업데이트

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  version-bump:
    name: 버전 자동 증가
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 현재 버전 확인
        id: current_version
        run: |
          CURRENT_VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //' | tr -d ' ')
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "현재 버전: $CURRENT_VERSION"

      - name: 새 버전 계산 (patch 버전 증가)
        id: version
        run: |
          VERSION_LINE="${{ steps.current_version.outputs.current_version }}"
          VERSION=$(echo $VERSION_LINE | cut -d'+' -f1)
          BUILD_NUMBER=$(echo $VERSION_LINE | cut -d'+' -f2)

          # patch 버전 증가 (1.0.0 → 1.0.1)
          IFS='.' read -ra VERSION_PARTS <<< "$VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}+${BUILD_NUMBER}"

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "새 버전: $NEW_VERSION"

      - name: pubspec.yaml 업데이트
        run: |
          sed -i "s/version: .*/version: ${{ steps.version.outputs.new_version }}/" pubspec.yaml
          echo "pubspec.yaml 업데이트 완료: ${{ steps.version.outputs.new_version }}"

      - name: 버전 업 커밋
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pubspec.yaml
          git commit -m "ROMROM-FE 버전 정보 관리 : chore: 버전 ${{ steps.version.outputs.new_version }} : https://github.com/TEAM-ROMROM/RomRom-FE/issues/167" || exit 0
          git push

      - name: Git 태그 생성
        run: |
          git tag "v${{ steps.version.outputs.new_version }}"
          git push origin "v${{ steps.version.outputs.new_version }}"

      - name: 버전 업 완료 알림
        run: |
          echo "버전 업데이트 완료!"
          echo "이전 버전: ${{ steps.current_version.outputs.current_version }}"
          echo "새 버전: ${{ steps.version.outputs.new_version }}"
          echo "커밋: ${{ github.sha }}" 