name: ROMROM-FRONT-Firebase-Distribution

on:
  push:
    branches: ["main", "test"]
  workflow_dispatch:

jobs:
  # 안드로이드 빌드
  build_android:
    name: Build & Deploy Android
    runs-on: ubuntu-latest

    steps:
      # (1) 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v3

      # (2) Flutter 설치
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.3"
          channel: stable

      # (3) .env 생성
      - name: Create .env file from secret
        run: |
          echo "${{ secrets.ENV }}" > .env
          export $(cat .env | xargs)

      # (4) 의존성 설치
      - name: Install dependencies
        run: flutter pub get

      # (5) Android 빌드 (apk or appbundle)
      - name: Build APK
        run: flutter build apk --release

      - name: Upload artifact (APK)
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # (7) Firebase CLI 설치
      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      # (8) Firebase 이용해 안드로이드 배포
      - name: Distribute Android to Firebase
        run: |
          firebase appdistribution:distribute \
          build/app/outputs/flutter-apk/app-release.apk \
          --app "${{ secrets.FIREBASE_ANDROID_APP_ID }}" \
          --groups "testers" \
          --release-notes "Android Build for ${{ github.ref_name }}" \
          --token "${{ secrets.FIREBASE_TOKEN }}"

  # IOS 빌드
  build_ios:
    name: Build & Deploy iOS
    runs-on: macos-latest # iOS 빌드는 macOS에서 실행

    steps:
      # (1) 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v3

      # (2) Flutter 설치
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.3"
          channel: stable

      # (3) 의존성 설치
      - name: Install dependencies
        run: flutter pub get

      # (4) IOS 빌드
      - name: Build iOS
        run: flutter build ipa --release

      # (5) Firebase CLI 설치
      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      # (6) Firebase에 IOS 배포
      - name: Distribute iOS to Firebase
        run: |
          firebase appdistribution:distribute \
            build/ios/archive/Runner.ipa \
            --app "${{ secrets.FIREBASE_IOS_APP_ID }}" \
            --groups "testers" \
            --release-notes "iOS Build for ${{ github.ref_name }}" \
            --token "${{ secrets.FIREBASE_TOKEN }}"
